
source 'https://github.com/CocoaPods/Specs.git'

target 'Emotism' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskTape

platform :ios, '11.0'

pod 'CoreMLHelpers', git: 'https://github.com/hollance/CoreMLHelpers.git', branch: 'master'


post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end

end
